base_link:
  # for autoware base_link refers to ROS2 nav base_footprint
  # see (https://autowarefoundation.github.io/autoware-documentation/pr-480/how-to-guides/integrating-autoware/creating-vehicle-and-sensor-model/creating-sensor-model/)
  # vehicle dimensions/base_link (https://autowarefoundation.github.io/autoware-documentation/pr-480/design/autoware-interfaces/components/vehicle-dimensions/)
  sensor_kit_base_link:
    x: 0.0
    y: 0.0
    z: 0.033  # rear_axle to ground == wheel radius == 0.033. Added to sensors.xacro
    roll: 0.0
    pitch: 0.0
    yaw: 0.0