/**:
  ros__parameters:
    filter1:
      name: box_filter  # to remove parts of the car, e.g antennae from the laserscan
      type: laser_filters/LaserScanBoxFilter
      params:
        box_frame: lidar
        max_x: 0.1
        max_y: 0.1
        max_z: 0.5
        min_x: -0.4
        min_y: -0.1
        min_z: -0.5

        invert: false # activate to remove all points outside of the box

#    filter2:
#      name: interpolation
#      type: laser_filters/InterpolationFilter